version: "3.8"

services:
  app:
    build: .
    container_name: web-cms-app
    restart: always
    env_file:
      - ./.env
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    volumes:
      - uploads:/app/uploads
    environment:
      - MONGODB_URI=mongodb://mongo:27017/cms-player
      - UPLOAD_DIR=uploads
    command: sh -c "npm run init-db && npm run dev"

  mongo:
    image: mongo:6.0
    container_name: web-cms-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  uploads:
  mongo_data:
